# Generated by Django 4.1 on 2022-08-21 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ObjectInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_name", models.CharField(max_length=100)),
                ("object_id", models.CharField(max_length=25)),
                ("norad_cat_id", models.IntegerField()),
                ("object_type", models.CharField(max_length=15)),
                ("ops_status_code", models.CharField(blank=True, max_length=15)),
                ("owner", models.CharField(max_length=15)),
                ("launch_date", models.DateField()),
                ("launch_site", models.CharField(max_length=15)),
                ("decay_date", models.CharField(blank=True, max_length=15)),
                ("period", models.CharField(blank=True, max_length=15)),
                ("inclination", models.CharField(blank=True, max_length=15)),
                ("apogee", models.CharField(blank=True, max_length=15)),
                ("perigee", models.CharField(blank=True, max_length=15)),
                ("rcs", models.CharField(blank=True, max_length=15)),
                ("data_status_code", models.CharField(blank=True, max_length=15)),
                ("orbit_center", models.CharField(max_length=15)),
                ("orbit_type", models.CharField(max_length=15)),
            ],
        ),
    ]
